import { drizzle } from 'drizzle-orm/d1';

import type { CloudflareEmailBinding } from '@/extensions/email';

// `.open-next/worker.js` is generated by `pnpm cf:build`.
import handler from './.open-next/worker.js';

type WorkerEnvironment = {
  DB: UnsafeAny;
  EMAIL: CloudflareEmailBinding;
  EMAIL_FROM_ADDRESS?: string;
  EMAIL_FROM_NAME?: string;
  EMAIL_REPLY_TO?: string;
  NEXT_PUBLIC_APP_URL?: string;
};

const worker = {
  fetch: handler.fetch,

  async scheduled(_event: unknown, env: WorkerEnvironment) {
    const baseUrl = env.NEXT_PUBLIC_APP_URL || 'https://www.babyboogey.com';
    const [{ getEmailServiceWithBinding }, { runCustomerEmailMaintenance }] =
      await Promise.all([
        import('@/shared/services/email'),
        import('@/shared/services/customer-lifecycle-email'),
      ]);
    const database = drizzle(env.DB);
    const emailService = getEmailServiceWithBinding(env.EMAIL, {
      fromEmail: env.EMAIL_FROM_ADDRESS,
      fromName: env.EMAIL_FROM_NAME,
      replyTo: env.EMAIL_REPLY_TO,
    });
    await runCustomerEmailMaintenance({
      database,
      emailService,
      baseUrl,
    });
  },
};

export default worker;

// Required when OpenNext's generated worker exposes cache Durable Objects.
export { DOQueueHandler, DOShardedTagCache } from './.open-next/worker.js';
